# Generated by Django 6.0.4 on 2026-04-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_playlist',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
