# Generated by Django 6.0.4 on 2026-04-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_hls_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_1080p',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='hls_480p',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='hls_720p',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
