# Generated by Django 6.0.4 on 2026-04-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_hls_1080p_video_hls_480p_video_hls_720p'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
