# Generated by Django 6.0.4 on 2026-05-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('nature', 'Nature'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('documentary', 'Documentary')], default='entertainment', max_length=50),
        ),
    ]
